version: "3.8"

networks:
  services:
    driver: bridge

services:
  ports-service:
    build:
      context: "./portsService"
    restart: on-failure
    environment:
      GRPC_PORT: ":9090"

    networks:
      services:
        aliases:
          - ports-service
    ports:
      - 9090:9090 # gGRPC service


  

  

